services:
  # api:
  #   build: .
  #   environment:
  #     - DB_URL=db
  #     - DB_USERNAME=micronote
  #     - DB_PASSWORD=asecurepassword
  #     - JWT_SECRET=113041444b202da38545c4b24448d30550f6764f1af267da3be60298b3ed2492
  #   depends_on:
  #     - db
  #   ports:
  #     - "80:80"
  api:
    image: ghcr.io/bbunks/notes
    environment:
      - DB_URL=db
      - DB_USERNAME=micronote
      - DB_PASSWORD=asecurepassword
      - JWT_SECRET=113041444b202da38545c4b24448d30550f6764f1af267da3be60298b3ed2492
    depends_on:
      - db
    ports:
      - "80:80"
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: "micronote"
      MYSQL_USER: "micronote"
      MYSQL_PASSWORD: "asecurepassword"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
